### ISSUE TITLE
Missing packet 0x42 in MCPE documentation/generated packets

### ISSUE THREAD

**Issue by MrPowerGamerBR** [sel-project/sel-utils#1]
https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET/Net/MCPE%20Protocol%20Documentation.md

0x42 is the "Mcpe Clientbound Map Item Data" in MiNET documentation, however that packet is missing on the MCPE protocol documentation here, I don't know if this was intentional so I decided to report the issue here.

**Comment by MrPowerGamerBR** [comment]
Fixed https://github.com/sel-project/sel-utils/commit/32aa56faa4602b68f682f09ce9f357607c768d9f 👍

**Comment by Kripth** [comment]
I'm not sure about the field types, I'll do some tests.
