### ISSUE TITLE
Related project

### ISSUE THREAD

**Issue by rom1504** [sel-project/sel-utils#13]
Hey,
Interesting project !
Just wanted to let you know about https://github.com/PrismarineJS/minecraft-data and https://github.com/ProtoDef-io/ProtoDef
It seems our projects are similar, maybe there are some stuff we could collaborate on.

How do you get the xml files, do you write them all manually ?

Anyway, nice work ;)

**Comment by Kripth** [comment]
I already knew PrismarineJS' minecraft-data but unfortunately MCPE's protocol wasn't provided and I had to start my own project.
I'm thinking about moving the data to another repo(s) and organise it better, I really think we could collaborate on that.

XML files are mostly written by hand or converted and now maintained by hand.

**Comment by ghost** [comment]
If you're still interested in working on this, we'd love to chat with you in https://gitter.im/PrismarineJS/minecraft-data
