### ISSUE TITLE
Missing TransferPacket in MCPE 101 protocol

### ISSUE THREAD

**Issue by MrPowerGamerBR** [sel-project/sel-utils#3]
Info: https://twitter.com/shoghicp/status/826665876057423873

![http://i.imgur.com/WGH09po.png](http://i.imgur.com/WGH09po.png)

**Comment by Kripth** [comment]
I'm working on it!

**Comment by MrPowerGamerBR** [comment]
@Kripth thanks! 😄

**Comment by MrPowerGamerBR** [comment]
Fixed in https://github.com/sel-project/sel-utils/commit/314ee4051d1158ab0b9f703d818cd27e8c50fe26

Thanks @Kripth for creating the most indepth MCPE protocol documentation I even seen! 👍
