### ISSUE TITLE
ClientBoundMapItemData

### ISSUE THREAD

**Issue by inxomnyaa** [sel-project/sel-utils#6]
Hey
Wanted to let you know the packet got sucessfully encoded, you might want to add it to the website
https://github.com/pmmp/PocketMine-MP/blob/c1478b1cc09bab01840afd8f7e587c76f742135a/src/pocketmine/network/mcpe/protocol/ClientboundMapItemDataPacket.php

**Comment by Kripth** [comment]
It's used in a different way but it has already been updated: https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket102.xml#L1065
